const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  FETCH_USER_CART_SUCCESS: 'FETCH_USER_CART_SUCCESS',
  FETCH_USER_CART_FAILURE: 'FETCH_USER_CART_FAILURE',
};

export default CartActionTypes;
